apiVersion: v1
kind: Service
metadata:
  name: video-processor-service
  labels:
    app: video-processor-service
spec:
  type: ClusterIP
  selector:
    app: video-processor-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
